#!/bin/sh

[ "$ACTION" = "ifdown" ] && [ "$INTERFACE" = "wan" ] || exit 0

logger -t LTE_Reconnect "检测到WAN口断开，触发重连"
sleep 10  # 等待10秒避免冲突

# 执行重连
gcom -d /dev/ttyUSB0 -s /proc/self/fd/0 << EOF
opengt
 set com 115200n81
 set comecho off
 set senddelay 0.05
 waitquiet 0.5 0.5
 flash 0.1

:start
 send "AT+CFUN=1^m"
 waitfor 5 "OK"
 send 'AT+CGDCONT=1,"IPV4V6"^m'
 waitfor 10 "OK"
 send 'AT+CGACT=1,1^m'
 waitfor 10 'OK'
 send 'AT+ZGACT=1,1^m'
 waitfor 10 'OK'
EOF

logger -t LTE_Reconnect "LTE重连操作已完成"